spring.application.name=task-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/task_tracker
spring.datasource.username=task_tracker
spring.datasource.password=task_tracker

spring.jpa.hibernate.ddl-auto=validate